apiVersion: v1
kind: Service
metadata:
  name: tasks-api-service
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "tasks-api-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: tasks-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: tasks-api-config
spec:
  timeoutSec: 21600
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    requestPath: /
    port: 8080
