apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tasks
  template:
    metadata:
      labels:
        app: postgres-tasks
    spec:
      containers:
        - name: postgres-tasks
          image: postgres:16.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "abc12345"
            - name: POSTGRES_DB
              value: "tasks"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-tasks-service
spec:
  type: ClusterIP
  selector:
    app: postgres-tasks
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-tasks-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
